---

- name: ensure users are created
  mysql_user:
    name: "{{ item.name }}"
    host: "{{ item.host | default('localhost') }}"
    password: "{{ item.password }}"
    priv: "{{ item.privileges | default('*.*:USAGE') }}"
    append_privs: "{{ item.append_privileges | default('no') }}"
  with_items: "{{ mysql_users }}"

- name: Fix password authentication method for users
  command: "mysql -NBe \"ALTER USER '{{ item.name }}'@'{{ item.host | default('localhost') }}' IDENTIFIED WITH mysql_native_password BY '{{ item.password }}'\""
  with_items: "{{ mysql_users }}"
